# Cấu hình chung cho mọi profile
spring:
    profiles:
      active: @spring.profiles.active@
    jpa:
      open-in-view: false
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
